# Site settings
title: Niklas Lindblad
header: Niklas Lindblad
description: A blog about software engingeering, programming and agile development.
url: "http://niklind.github.io"
permalink: /:title/
baseurl: ""

font-awesome: true # make this false if you don't need font-awesome
social-sharing: false # make this false if you don't need rrssb

# Build settings
markdown: kramdown

exclude: ["README.md"]
