# Site settings
title: Niklas Lindblad
header: Niklas Lindblad
description: A blog about software engineering, tools and agile practices.
url: ""
permalink: /:title/
baseurl: ""

font-awesome: false # make this false if you don't need font-awesome
social-sharing: false # make this false if you don't need rrssb
jquery: false

# Build settings
markdown: kramdown

sass:
    style: compressed

navigation:
  - title: "GitHub"
    url: "https://github.com/niklind"
  - title: "Twitter"
    url: "https://twitter.com/niklind"
  - title: "LinkedIn"
    url: "https://www.linkedin.com/in/niklaslindblad"

exclude: ["README.md"]
